if (WIN32)
elseif (APPLE)
elseif (UNIX)
    include(GNUInstallDirs)

    if(NOT DEFINED AQUA_EXECUTABLE_PATH)
        set(AQUA_EXECUTABLE_PATH "sunshine")
    endif()

    if(AQUA_BUILD_FLATPAK)
        set(AQUA_SERVICE_START_COMMAND "ExecStart=flatpak run --command=sunshine ${PROJECT_FQDN}")
        set(AQUA_SERVICE_STOP_COMMAND "ExecStop=flatpak kill ${PROJECT_FQDN}")
    else()
        set(AQUA_SERVICE_START_COMMAND "ExecStart=${AQUA_EXECUTABLE_PATH}")
        set(AQUA_SERVICE_STOP_COMMAND "")
    endif()
endif()
